### ISSUE TITLE
Handle missing graph configuration better

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#176]
I've been implementing graph configurations for the StateMod dataset viewer.  Sometimes I don't get get the filenames or file content exactly right.  The InfoMapper gives the error about loading the map file.  It should continue to display the map.  The console message seems OK and I can track down.  We don't want users of deployed sites to see a map crash.... hopefully the configuration will be good at that point, but  in any case want the user to experience as little disruption as possible.

**Comment by Nightsphere** [comment]
The error handling has been steadily changed throughout development so that only huge, Leaflet map creation errors in the map configuration file will result in a map error in the InfoMapper. Everything else will keep displaying the map as it was before, with an error or warning message in the DevTools window. Closing the issue.
