### ISSUE TITLE
Specifying opacity for single symbol causes layer to not draw?

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#288]
I tried to add a polygon with single symbol in GeoProcessor.  The following works:

```
SetGeoLayerViewSingleSymbol(GeoLayerViewID="StateBoundaryLayerView",Name="State boundary symbol",Description="State boundary in black.",Properties="color:#000000,fillColor:#000000,fillOpacity:0.0,weight:2")
```

However, setting the opacity as follows caused the layer to not display:

```
SetGeoLayerViewSingleSymbol(GeoLayerViewID="StateBoundaryLayerView",Name="State boundary symbol",Description="State boundary in black.",Properties="color:#000000,opacity:0.0,fillColor:#000000,fillOpacity:0.0,weight:2")
```

**Comment by Nightsphere** [comment]
I believe what happened here was the layer was created, but because both opacity and fillOpacity were set to `0.0`, the border didn't show up. Recreating the first example on a point map, I get the following:

![image](https://user-images.githubusercontent.com/22484403/154588110-0b6a7922-29c6-4155-8d34-3cb9439ecb5b.png)

Without the opacity given, it defaults to one. Since the fillOpacity is set to 0, only the outline of the shape is visible. This makes sense. For the second example, the opacity of the entire shape is now set to 0 as well, so nothing shows up on the map or the side bar, even though the still technically exist. Indeed, the following image shows the mouse hovering on the same point as the first image, and the same popup displays. 

![image](https://user-images.githubusercontent.com/22484403/154587060-351fdb86-84ba-4847-9498-0a7996e3d0c7.png)

Changing the opacity and/or fillOpacity to something greater than 1 should show something on the map. Closing this issue.
